"use client";

import { useMemo, useState } from "react";
import { OpportunityCard, SectionTitle } from "@/components/ui";
import { useStore } from "@/lib/store";
import { CATEGORIES, type Category, type Opportunity } from "@/lib/types";

export function RecsBanner() {
  const { recs, refreshRecs } = useStore();
  if (recs.status !== "done" && recs.status !== "error")
    return <p role="status" className="rounded-xl bg-lav-100 p-3 text-sm text-plum-800">✨ Asking Gemini to match opportunities to your profile…</p>;
  if (recs.status === "error")
    return (
      <div role="alert" className="flex flex-wrap items-center gap-3 rounded-xl bg-red-50 p-3 text-sm text-red-800">
        Could not load recommendations: {recs.error}
        <button onClick={refreshRecs} className="rounded-full bg-red-700 px-3 py-1 text-white">Retry</button>
      </div>
    );
  if (recs.status !== "done") return null;
  const r = recs.result;
  return r.source === "gemini" ? (
    <div className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900">
      <span>✨ <strong>AI recommendations generated by Google Gemini</strong> ({r.model}) from your profile. May be imperfect — verify with official sources.</span>
      <button onClick={refreshRecs} className="rounded-full border border-emerald-700 px-3 py-1 font-semibold">Regenerate</button>
    </div>
  ) : (
    <div role="status" className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-gold-100 p-3 text-sm text-[#6b4a00]">
      <span>⚠ <strong>Fallback mode — not AI.</strong> Simple interest/keyword matching is shown because Gemini is unavailable ({r.note}).</span>
      <button onClick={refreshRecs} className="rounded-full border border-[#6b4a00] px-3 py-1 font-semibold">Try Gemini again</button>
    </div>
  );
}

export function useRankedRecs() {
  const { recs, opportunities } = useStore();
  return useMemo(() => {
    if (recs.status !== "done") return [];
    const byId = new Map(opportunities.map((o) => [o.id, o]));
    return recs.result.recommendations
      .map((r) => ({ rec: r, opp: byId.get(r.id) }))
      .filter((x): x is { rec: typeof x.rec; opp: Opportunity } => Boolean(x.opp));
  }, [recs, opportunities]);
}

export function PopularThisWeek({ limit = 3 }: { limit?: number }) {
  const { opportunities, countFor, countsMode } = useStore();
  const ranked = [...opportunities].sort((a, b) => countFor(b.id).week - countFor(a.id).week).slice(0, limit);
  return (
    <section>
      <SectionTitle
        sub={
          countsMode === "firestore"
            ? "Ranked by new active catches this Monday–Sunday (Pacific). Catches are anonymous browsers, not unique students."
            : "Illustrative demo numbers — the shared database is not connected, so these are NOT real community activity."
        }
      >
        Popular This Week {countsMode === "demo" && <span className="align-middle text-xs font-semibold text-[#7a5600]">(demo data)</span>}
      </SectionTitle>
      <ol className="grid gap-3 md:grid-cols-3">
        {ranked.map((o, i) => (
          <li key={o.id} className="rounded-2xl border border-lav-200 bg-white p-4">
            <p className="text-xs font-bold text-gold-500">#{i + 1}</p>
            <p className="font-bold text-plum-900">{o.title}</p>
            <p className="text-sm text-plum-700">♥ {countFor(o.id).week} this week · {countFor(o.id).total} total</p>
          </li>
        ))}
      </ol>
    </section>
  );
}

export function Discover() {
  const { opportunities } = useStore();
  const ranked = useRankedRecs();
  const [cat, setCat] = useState<Category | "All">("All");
  const [kind, setKind] = useState<"all" | "event" | "application">("all");
  const all = opportunities.filter((o) => (cat === "All" || o.category === cat) && (kind === "all" || o.kind === kind));
  return (
    <div className="space-y-8">
      <header>
        <h1 className="text-3xl font-extrabold text-plum-900">Discover</h1>
        <p className="text-slate-600">Opportunities matched to your profile and schedule.</p>
      </header>
      <RecsBanner />
      <section>
        <SectionTitle>Recommended For You</SectionTitle>
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
          {ranked.slice(0, 3).map(({ opp, rec }) => (
            <OpportunityCard key={opp.id} o={opp} rec={rec} />
          ))}
        </div>
      </section>
      <PopularThisWeek />
      <section>
        <SectionTitle>Explore All Opportunities</SectionTitle>
        <div className="mb-4 flex flex-wrap gap-2" role="group" aria-label="Filters">
          {(["All", ...CATEGORIES] as const).map((c) => (
            <button
              key={c}
              onClick={() => setCat(c)}
              aria-pressed={cat === c}
              className={`rounded-full border px-3 py-1 text-sm font-semibold ${cat === c ? "border-plum-800 bg-plum-800 text-white" : "border-lav-300 bg-white text-plum-800 hover:bg-lav-100"}`}
            >
              {c}
            </button>
          ))}
          <span className="mx-1 w-px bg-lav-300" />
          {([["all", "All types"], ["event", "Events"], ["application", "Applications"]] as const).map(([k, l]) => (
            <button
              key={k}
              onClick={() => setKind(k)}
              aria-pressed={kind === k}
              className={`rounded-full border px-3 py-1 text-sm font-semibold ${kind === k ? "border-gold-400 bg-gold-300 text-plum-900" : "border-lav-300 bg-white text-plum-800 hover:bg-lav-100"}`}
            >
              {l}
            </button>
          ))}
        </div>
        {all.length === 0 ? (
          <p className="text-slate-600">No opportunities match these filters.</p>
        ) : (
          <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
            {all.map((o) => (
              <OpportunityCard key={o.id} o={o} rec={ranked.find((r) => r.opp.id === o.id)?.rec} />
            ))}
          </div>
        )}
      </section>
    </div>
  );
}
